#!/bin/bash

# Auto-commit and PR workflow script
# 每次完成重要工作後執行

set -e

echo "🔄 Auto-commit and PR workflow starting..."

# 檢查是否在 Git 倉庫中
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "❌ Not in a git repository"
    exit 1
fi

# 檢查是否有變更
if [[ -z $(git status --porcelain) ]]; then
    echo "✅ No changes to commit"
    exit 0
fi

# 生成時間戳
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BRANCH_NAME="auto-arch-${TIMESTAMP}"

# 自動添加所有變更
echo "📝 Adding all changes..."
git add .

# 生成智能提交信息
echo "📋 Generating commit message..."
CHANGES=$(git diff --cached --name-only | sed 's/^/- /')

COMMIT_MSG="feat: ${TIMESTAMP} - Auto-architectural improvements

📋 Changes:
${CHANGES}

🤖 Generated by SuperNinja workflow
📍 This commit ensures all architectural work is preserved in PR"

# 提交變更
echo "💾 Committing changes..."
git commit -m "$COMMIT_MSG"

# 創建並切換到新分支
echo "🌿 Creating branch ${BRANCH_NAME}..."
git checkout -b $BRANCH_NAME

# 推送到遠程
echo "📤 Pushing to remote..."
git push -u origin $BRANCH_NAME

# 檢查是否有 GitHub CLI
if command -v gh &> /dev/null; then
    echo "🔀 Creating Pull Request..."
    gh pr create \
        --title "Auto-architectural updates ${TIMESTAMP}" \
        --body "🤖 Automated architectural improvements

This PR contains:
- File system governance enhancements
- Validation system improvements
- Policy updates and refactoring

**Generated by SuperNinja workflow at ${TIMESTAMP}**

## 📊 Summary
- All changes automatically committed and tracked
- Ensures no architectural work is lost
- Follows enterprise-grade development practices

## ✅ Next Steps
1. Review the changes
2. Run tests if applicable
3. Merge after approval" \
        --assignee @me \
        --label "auto-generated,architectural"
    
    echo "✅ Pull Request created successfully!"
else
    echo "⚠️  GitHub CLI not found. Please create PR manually:"
    echo "   Branch: ${BRANCH_NAME}"
    echo "   Or install GitHub CLI: https://cli.github.com/"
fi

echo "🎉 Auto-commit and PR workflow completed!"
echo "📋 Summary:"
echo "   - Changes committed: ${COMMIT_MSG}"
echo "   - Branch created: ${BRANCH_NAME}"
echo "   - Remote push: ✅"
echo "   - PR status: $([ -x "$(command -v gh)" ] && echo "✅ Created" || echo "⚠️  Manual")"