# Root Specification Validation Gate
# Immutable validation gate configuration for baseline verification
# Part of: controlplane/baseline/validation

metadata:
  gate_name: root-specs-validation
  version: "1.0.0"
  description: "Validation gate for root namespace baseline specifications"
  immutable: true

# Validation Gate Configuration
gate:
  enabled: true
  enforcement: strict
  failure_action: block
  evidence_required: true
  
# Validation Stages
stages:
  
  # Stage 1: Structural Validation
  structural:
    order: 1
    description: "Verify file existence and basic structure"
    required: true
    checks:
      - name: "baseline_directory_exists"
        description: "Verify baseline directory structure"
        type: filesystem
        target: "controlplane/baseline"
        
      - name: "config_files_exist"
        description: "Verify all config files present"
        type: filesystem
        targets:
          - "controlplane/baseline/config/root.config.yaml"
          - "controlplane/baseline/config/root.devices.map"
          - "controlplane/baseline/config/root.governance.yaml"
          - "controlplane/baseline/config/root.integrity.yaml"
          - "controlplane/baseline/config/root.kernel.map"
          - "controlplane/baseline/config/root.modules.yaml"
          - "controlplane/baseline/config/root.naming-policy.yaml"
          - "controlplane/baseline/config/root.provenance.yaml"
          - "controlplane/baseline/config/root.super-execution.yaml"
          - "controlplane/baseline/config/root.trust.yaml"
          
      - name: "spec_files_exist"
        description: "Verify all specification files present"
        type: filesystem
        targets:
          - "controlplane/baseline/specifications/root.specs.context.yaml"
          - "controlplane/baseline/specifications/root.specs.logic.yaml"
          - "controlplane/baseline/specifications/root.specs.mapping.yaml"
          - "controlplane/baseline/specifications/root.specs.naming.yaml"
          - "controlplane/baseline/specifications/root.specs.references.yaml"
          
      - name: "registry_files_exist"
        description: "Verify all registry files present"
        type: filesystem
        targets:
          - "controlplane/baseline/registries/root.registry.modules.yaml"
          - "controlplane/baseline/registries/root.registry.devices.yaml"
          
      - name: "integration_files_exist"
        description: "Verify integration files present"
        type: filesystem
        targets:
          - "controlplane/baseline/integration/root.integration.yaml"
          
      - name: "documentation_exists"
        description: "Verify documentation present"
        type: filesystem
        targets:
          - "controlplane/baseline/documentation/BASELINE_ARCHITECTURE.md"
    
  # Stage 2: Syntax Validation
  syntax:
    order: 2
    description: "Verify YAML syntax and structure"
    required: true
    checks:
      - name: "yaml_syntax_valid"
        description: "All YAML files parse correctly"
        type: yaml_parse
        targets: "controlplane/baseline/**/*.yaml"
        
      - name: "yaml_structure_valid"
        description: "YAML files have required top-level keys"
        type: yaml_structure
        requirements:
          config: ["metadata", "configuration"]
          specs: ["metadata", "specifications"]
          registry: ["metadata", "devices", "modules"]
          integration: ["metadata", "integration_points"]
  
  # Stage 3: Semantic Validation
  semantic:
    order: 3
    description: "Verify logical consistency and completeness"
    required: true
    checks:
      - name: "naming_consistency"
        description: "All names follow naming policy"
        type: semantic
        validator: "validate_naming_consistency"
        
      - name: "reference_completeness"
        description: "All references resolve correctly"
        type: semantic
        validator: "validate_references"
        
      - name: "trust_alignment"
        description: "Trust levels are consistent"
        type: semantic
        validator: "validate_trust_levels"
        
      - name: "registry_completeness"
        description: "All referenced items are registered"
        type: semantic
        validator: "validate_registry_completeness"
  
  # Stage 4: Integration Validation
  integration:
    order: 4
    description: "Verify cross-component integration"
    required: true
    checks:
      - name: "config_spec_alignment"
        description: "Configs align with specifications"
        type: integration
        validator: "validate_config_spec_alignment"
        
      - name: "module_device_consistency"
        description: "Module-device mappings are consistent"
        type: integration
        validator: "validate_module_device_consistency"
        
      - name: "governance_trust_alignment"
        description: "Governance aligns with trust model"
        type: integration
        validator: "validate_governance_trust_alignment"
        
      - name: "naming_registry_consistency"
        description: "Registry entries follow naming policies"
        type: integration
        validator: "validate_naming_registry_consistency"
  
  # Stage 5: Security Validation
  security:
    order: 5
    description: "Verify security properties"
    required: true
    checks:
      - name: "immutability_enforced"
        description: "Baseline files are read-only"
        type: security
        validator: "validate_immutability"
        
      - name: "integrity_verified"
        description: "File integrity checksums valid"
        type: security
        validator: "validate_integrity"
        
      - name: "provenance_tracked"
        description: "Provenance information present"
        type: security
        validator: "validate_provenance"
        
      - name: "trust_boundaries_enforced"
        description: "Trust boundaries are enforced"
        type: security
        validator: "validate_trust_boundaries"

# Validation Vectors
vectors:
  source: "controlplane/baseline/validation/vectors/root.validation.vectors.yaml"
  required: true
  
# Evidence Configuration
evidence:
  enabled: true
  output_directory: "controlplane/overlay/evidence/validation"
  formats:
    - json
    - yaml
  artifacts:
    - validation_report
    - test_results
    - integrity_checksums
    - audit_log
  retention:
    days: 90
    archive: true

# Reporting
reporting:
  enabled: true
  formats:
    - json
    - markdown
  outputs:
    - file: "controlplane/overlay/evidence/validation/validation.report.json"
      format: json
    - file: "controlplane/overlay/evidence/validation/validation.report.md"
      format: markdown
  include:
    - summary
    - detailed_results
    - failed_checks
    - warnings
    - recommendations

# Failure Handling
failure_handling:
  on_structural_failure:
    action: block
    message: "Critical: Baseline structure incomplete"
    
  on_syntax_failure:
    action: block
    message: "Critical: YAML syntax errors detected"
    
  on_semantic_failure:
    action: block
    message: "Critical: Logical inconsistencies detected"
    
  on_integration_failure:
    action: block
    message: "Critical: Integration constraints violated"
    
  on_security_failure:
    action: block
    message: "Critical: Security requirements not met"

# Success Criteria
success_criteria:
  all_stages_pass: true
  no_critical_failures: true
  evidence_generated: true
  report_created: true
  
# Validation Metadata
validation_metadata:
  track_duration: true
  track_resource_usage: false
  log_level: info
  verbose: false